# Create a namespace for the app
apiVersion: v1
kind: Namespace
metadata:
  name: kiada
---
# Create a deployment for the app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiada
  namespace: kiada
  labels:
    app: kiada
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kiada
  template:
    metadata:
      labels:
        app: kiada
    spec:
      containers:
        - name: kiada-container
          image: kiada:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "70m"  # 0.070 CPU cores
              memory: "128Mi"
            limits:
              cpu: "100m"  # 0.100 CPU cores
              memory: "256Mi"
---
# Create a Service of type "LoadBalancer" to expose the app to the outside world
# Locally this does not fully work with `kind` because locally there is no
# external service to provision a LoadBalancer, so EXTERNAL-IP stays `<pending>`.
# Run `kubectl -n kiada get svc kiada-service` to see this.
#
# As a work around we can use `cloud-provider-kind` program that can connect to kind
# cluster and can provision a LB container for the services. Refer Chapter 3 notes.
apiVersion: v1
kind: Service
metadata:
  name: kiada-service
  namespace: kiada
spec:
  type: "LoadBalancer"
  selector:
    app: kiada        # This much match the Pod Label
  ports:
  - protocol: TCP
    port: 8080        # Port exposed by this service 
    targetPort: 8080  # Port your container is listening on
